version: 2


models:
  - name: stg_raw__parcel
    description: staged parcel date
    columns:
      - name: parcel_id
        tests:
          - unique
          - not_null
      - name: date_purchase
        tests:
          - not_null
  - name: stg_raw__parcel_product
    columns:
      - name: parcel_id
        tests:
          - not_null
    tests:
      - unique:
          column_name: 'parcel_id || "_" || model_name'
          