version: 2

models:
  - name: stg_raw__parcel
    description: parcel data per parcel
    columns:
      - name: parcel_id
        description: the id
        tests:
          - unique
          - not_null
  - name: stg_raw__parcel_product
    description: parcel data split by model
    columns:
      - name: parcel_id
        tests:
          - not_null
    tests:
      - unique:
          column_name: "parcel_id || '_' || model_name"